"""allow_multiple_bets

Revision ID: af696632583f
Revises: 0006_color_game
Create Date: 2026-04-21 14:10:56.302774

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa



revision = 'af696632583f'
down_revision = '0006_color_game'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_color_bets_user_round', 'color_bets', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_color_bets_user_round', 'color_bets', ['user_id', 'round_id'])
    # ### end Alembic commands ###

